name: ai
description: "A new Flutter project."

publish_to: 'none'

version: 0.8.4

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter_downloader: ^1.11.8
  permission_handler: ^11.3.1
  path_provider: ^2.0.11
  shared_preferences: ^2.3.2
  uuid: ^4.5.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0-nullsafety.2
  provider: ^6.1.2
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  flutter_dotenv: ^5.2.1
  google_generative_ai: ^0.4.6
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  flutter_markdown: ^0.7.4+1
  font_awesome_flutter: ^10.8.0
  file_picker: ^8.1.4
  cloud_firestore: ^5.4.5
  image_picker: ^1.1.2
  skeletonizer: ^1.4.2
  safe_text: ^1.0.7
  email_validator: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/vertexailogo.png
    - assets/vertexailogodarkwhite.png
    - assets/profile.png
    - assets/gemma.png
    - assets/mistral.png
    - assets/neo.png
    - assets/tinyllama.png
    - assets/phi.png
    - assets/gemini.png
    - assets/llama.png
    - assets/customai.png
    - assets/hermes.png
    - .env
