// suggestions.dart

final List<String> suggestions = [
  "Merhaba!",
  "Nasılsın?",
  "Bugün nasılsın?",
  "Günün nasıl geçti?",
  "Bana yardımcı olabilir misin?",
  "Teşekkür ederim.",
  "Rica ederim.",
  "Ne yapıyorsun?",
  "Ne hakkında konuşmak istersin?",
  "Anlayamadım, tekrarlar mısın?",
  "Nerelisin?",
  "Kaç yaşındasın?",
  "Hobilerin neler?",
  "Ne iş yapıyorsun?",
  "Hava bugün güzel, değil mi?",
  "Şu an meşgul müsün?",
  "Hafta sonu planların neler?",
  "İyi geceler.",
  "İyi günler.",
  "Hoşça kal.",
  "Görüşmek üzere.",
  "Seni özledim.",
  "Neler oluyor?",
  "Yeni bir şey var mı?",
  "Film izlemeyi sever misin?",
  "Kitap okumayı sever misin?",
  "Spor yapıyor musun?",
  "Müzik dinlemeyi sever misin?",
  "Hangi tür müzikleri seversin?",
  "En sevdiğin film nedir?",
  "Yemek yapmayı sever misin?",
  "Bugün ne yedin?",
  "Şaka yapıyorsun!",
  "Ciddi misin?",
  "Gerçekten mi?",
  "Harika!",
  "Üzgünüm.",
  "Sorun değil.",
  "Bunu duymak güzel.",
  "Seni anlıyorum.",
  "Katılıyorum.",
  "Katılmıyorum.",
  "Bunu daha önce duydum.",
  "Ne demek istiyorsun?",
  "Anladım.",
  "Bilmiyorum.",
  "Evet.",
  "Hayır.",
  "Belki.",
  "Tabii ki.",
  "Yardım edebilir miyim?",
  "Yardımına ihtiyacım var.",
  "Bir şey sorabilir miyim?",
  "Fikrin nedir?",
  "Sen ne düşünüyorsun?",
  "Zamanın var mı?",
  "Ne zaman müsaitsin?",
  "Çok meşgulüm.",
  "Bekle lütfen.",
  "Üzgünüm, anlamadım.",
  "Daha yavaş konuşabilir misin?",
  "Tekrar eder misin?",
  "Bugün tarih nedir?",
  "Saat kaç?",
  "Nerede buluşalım?",
  "Bunu nasıl yaparım?",
  "Yardım ettiğin için teşekkürler.",
  "Beni affet.",
  "Seni rahatsız ettiğim için özür dilerim.",
  "Bu doğru mu?",
  "Nerede yaşıyorsun?",
  "Nereye gidiyorsun?",
  "Burada mısın?",
  "Orada mısın?",
  "Dinliyor musun?",
  "İnternet bağlantım kötü.",
  "Seni duyamıyorum.",
  "Lütfen bana cevap ver.",
  "Nasıl hissediyorsun?",
  "İyi misin?",
  "Ne zaman görüşebiliriz?",
  "Seni daha sonra arayacağım.",
  "Bana biraz zaman ver.",
  "Neden?",
  "Çünkü...",
  "Ne demek istediğini anlıyorum.",
  "Sana katılıyorum.",
  "Bu harika bir fikir.",
  "Bunun hakkında ne düşünüyorsun?",
  "Bir önerin var mı?",
  "Neden olmasın?",
  "Çok iyi.",
  "Mümkün mü?",
  "Sen karar ver.",
  "Anlaştık.",
  "Yardımın için teşekkürler.",
  "Sıkıldım.",
  "Uykum var.",
  "Eğlenceli.",
  "İlginç.",
];
